update order_BillInfo 
set
BillFirstName = LTRIM(RTRIM(BillFirstName)),
BillLastName = LTRIM(RTRIM(BillLastName)),
BillEmailAddress = LTRIM(RTRIM(BillEmailAddress)),
BillAddress = LTRIM(RTRIM(BillAddress)),
BillAddress2 = LTRIM(RTRIM(BillAddress2)),
BillCity = LTRIM(RTRIM(BillCity)),
BillState = LTRIM(RTRIM(BillState)),
BillZipCode = LTRIM(RTRIM(BillZipCode)),
BillProvince = LTRIM(RTRIM(BillProvince)),
BillCountry = LTRIM(RTRIM(BillCountry)),
BillPhoneNumber = LTRIM(RTRIM(BillPhoneNumber)),
BillPhoneExt = LTRIM(RTRIM(BillPhoneExt)),
BillAltNumber = LTRIM(RTRIM(BillAltNumber)),
BillAltExt = LTRIM(RTRIM(BillAltExt)),
CardType = LTRIM(RTRIM(CardType)),
CardNumber = LTRIM(RTRIM(CardNumber)),
CardExpMonth = LTRIM(RTRIM(CardExpMonth)),
CardExpYear = LTRIM(RTRIM(CardExpYear)),
CardSecCode = LTRIM(RTRIM(CardSecCode)),
PONumber = LTRIM(RTRIM(PONumber)),
BillCompany = LTRIM(RTRIM(BillCompany))